sudo: false

language: go
go_import_path: github.com/ShakirzyanovArsen/temperature-backend
env:
  - GO111MODULE=off
go:
  - 1.11.x

notifications:
  email: false

git:
  depth: 1
install: true

script:
  - go build
  - go test -v ./...

